### ISSUE TITLE
Make all sampling functions batch capable

### ISSUE THREAD

**Issue by EiffL** [DifferentiableUniverseInitiative/DHOD#20]
For now, the sampling functions from HOD components are not batch capable. we should change that so that we can sample several batches at once, for VI purposes ;-)

**Comment by EiffL** [comment]
Just for reference @changhoonhahn , in Edward, the way to define a batch of like 10 samples is like so:
```
x = ed.Normal(loc=0, scale=1, sample_shape(10,))
```

**Comment by bhorowitz** [comment]
I was looking a bit at this a few days ago and wasn't quite sure what was the desired behavior? Currently it looks like you can feed in an arbitrary length array (batch size?) to NFW for both concentration and Rvir, and sample from it. You can even feed in a two dimensional array for rvir and con. What other functionality does it need to be "batch capable"?

**Comment by bhorowitz** [comment]
I finally realized what wasn't batch capable... I went through and fixed most of the functions in prep for the HMC model. I'll push it to the hmc branch soon.

**Comment by EiffL** [comment]
I think this is done.... closing
