### ISSUE TITLE
Implementation of NFW radial distribution

### ISSUE THREAD

**Issue by EiffL** [DifferentiableUniverseInitiative/DHOD#5]
Many thanks to @aphearin who pointed us to this reference:
  - https://arxiv.org/abs/1805.09550

This issue is to track comments during the implementation of this distribution. 

I've started implementing it as a proper TensorFlow Probability distribution in `u/EiffL/NFW`. The good news is that approximately a month ago, the Lambert W function got added to TensorFlow Probability so we got most of the work cut out for us :-D : https://github.com/tensorflow/probability/blob/d3dc1d657bc2386a86c69c445a8ae087e212cd05/tensorflow_probability/python/math/special.py#L141

**Comment by EiffL** [comment]
Also linked to the reference  above, here is a cute python implementation:
https://github.com/CullanHowlett/NFWdist

**Comment by EiffL** [comment]
This almost works, only one problem, the  TFP implementation of the Lambert W function sometimes gets stuck in an infinite loop. I should look at the scipy implementation to figure out what the difference is, and how to avoid that loop

**Comment by aphearin** [comment]
Hmm, I haven't noticed problems with this implementation, although I rewrote it myself so it's possible I wouldn't have. Do failures only happen for specific params?

**Comment by EiffL** [comment]
apparently not related to specific parameters, I haven't done extensive testing, but it gets stuck pretty often when sampling like10^4 samples

**Comment by EiffL** [comment]
and the code doesn't have a max number of iteration stopping criterion, so that doesnt seem safe ^^'

**Comment by aphearin** [comment]
Stopping criteria? Are we talking about the rnfw function in [this module](https://github.com/CullanHowlett/NFWdist/blob/master/python/NFWdist.py)? Where do stopping criteria come into this algorithm?

**Comment by EiffL** [comment]
ahh no sorry, miscommunication I think. I'm saying the TensorFlow Probability implementation of the Lambert W function gets stuck from time to time. That function is implmented using an iterative solver, have a look here:
https://github.com/DifferentiableUniverseInitiative/DHOD/blob/c4622c8fea043be6458b7385b192fec0b9fa3036/diffhod/math/special.py#L134

But they didn't include a max_iter or something like that, and apparently in practice it gets stuck from time to time in an infinite loop. I need to check the scipy implementation of `lambertw` to see how they achieve a more robust implementation.

The numpy code seems to be working great

**Comment by aphearin** [comment]
ahh, ok, my bad, got it.

**Comment by aphearin** [comment]
Worst comes to worst, you could always use the scipy implementation to train a simple MLP surrogate.

**Comment by EiffL** [comment]
Ok, so for future reference, here is the scipy  implementation, they have a few fixes for several special cases, but they still admit it can fail to converge from time to time:
https://github.com/scipy/scipy/blob/master/scipy/special/lambertw.pxd
For now however, I'm happy with just limiting the number of iterations to 100, I'll make a proper PR to TFP to propose a better fix.
Can now sample without problems 10^6 radii and get perfect match compared to theory:
![image](https://user-images.githubusercontent.com/861591/77700739-1a589c80-6fb5-11ea-93fd-18cabfbb0447.png)

10^6 sample time:
  - numpy: 298ms
  - TF (GPU accelerated): 81.9ms

**Comment by EiffL** [comment]
Ok, this has been super useful @all-contributors please add @aphearin for ideas

**Comment by EiffL** [comment]
This has been merged to master, it now has tests that compare the results to halotools.
